export type EntityTypePlural =
  | 'researchActivities'
  | 'researchPhases'
  | 'tags'
  | 'researchLogs'
  | 'researchSessions'
  | 'settings'
  | 'users'
  | 'activityFeeds'
  | 'activityDays'
  | 'activityLogs'
  | 'archivedTags'
  | 'archivedResearchActivities'
  | 'archivedResearchPhases'
  | 'archivedResearchSessions'
  | 'archivedResearchLogs';
